/*
 Navicat Premium Dump SQL

 Source Server         : 10.10.25.130-pgl
 Source Server Type    : PostgreSQL
 Source Server Version : 160008 (160008)
 Source Host           : 10.10.25.130:5432
 Source Catalog        : nodes
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160008 (160008)
 File Encoding         : 65001

 Date: 21/05/2026 11:36:37
*/


-- ----------------------------
-- Sequence structure for server_bi_tables_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."server_bi_tables_id_seq";
CREATE SEQUENCE "public"."server_bi_tables_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for server_urls_copy1_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."server_urls_copy1_id_seq";
CREATE SEQUENCE "public"."server_urls_copy1_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for server_urls_copy1_id_seq1
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."server_urls_copy1_id_seq1";
CREATE SEQUENCE "public"."server_urls_copy1_id_seq1" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for server_urls_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."server_urls_id_seq";
CREATE SEQUENCE "public"."server_urls_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for server_bi_tables
-- ----------------------------
DROP TABLE IF EXISTS "public"."server_bi_tables";
CREATE TABLE "public"."server_bi_tables" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "keys" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "val" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "type" int2 NOT NULL,
  "times" timestamp(0)
)
;

-- ----------------------------
-- Table structure for server_dicts
-- ----------------------------
DROP TABLE IF EXISTS "public"."server_dicts";
CREATE TABLE "public"."server_dicts" (
  "id" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "key" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "val" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "type" int2 NOT NULL,
  "note" varchar(100) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for server_hosts
-- ----------------------------
DROP TABLE IF EXISTS "public"."server_hosts";
CREATE TABLE "public"."server_hosts" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "domain" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "supplier" varchar(40) COLLATE "pg_catalog"."default" NOT NULL,
  "parent_id" int8,
  "supplier_account" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "status" int2 NOT NULL DEFAULT 0,
  "note" varchar(255) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6) NOT NULL,
  "app" varchar(16) COLLATE "pg_catalog"."default",
  "is_use" int2 NOT NULL DEFAULT 0,
  "ssl_at" timestamp(6),
  "supplier_id" int8,
  "is_self" int8 NOT NULL DEFAULT 0,
  "origin_domain" varchar(100) COLLATE "pg_catalog"."default",
  "scope" int2 NOT NULL DEFAULT 0,
  "beian" int2 NOT NULL DEFAULT 0
)
;
COMMENT ON COLUMN "public"."server_hosts"."app" IS 'app类型';
COMMENT ON COLUMN "public"."server_hosts"."ssl_at" IS '证书有效期';
COMMENT ON COLUMN "public"."server_hosts"."scope" IS '0全球，不包含中国内地,1全球,2仅中国内地';
COMMENT ON COLUMN "public"."server_hosts"."beian" IS '是否备案';

-- ----------------------------
-- Table structure for server_logs
-- ----------------------------
DROP TABLE IF EXISTS "public"."server_logs";
CREATE TABLE "public"."server_logs" (
  "id" int8 NOT NULL,
  "t" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "host" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "note" varchar(10000) COLLATE "pg_catalog"."default" NOT NULL,
  "created_at" timestamp(6) NOT NULL
)
;

-- ----------------------------
-- Table structure for server_nodes
-- ----------------------------
DROP TABLE IF EXISTS "public"."server_nodes";
CREATE TABLE "public"."server_nodes" (
  "id" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "in_ip" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "in_ip_pwd" varchar(50) COLLATE "pg_catalog"."default",
  "in_ip_user" varchar(20) COLLATE "pg_catalog"."default",
  "out_ip" varchar(20) COLLATE "pg_catalog"."default",
  "out_ip_user" varchar(20) COLLATE "pg_catalog"."default",
  "out_ip_pwd" varchar(50) COLLATE "pg_catalog"."default",
  "dw" int4,
  "out_ip_port" int4,
  "in_ip_port" int4,
  "note" varchar(500) COLLATE "pg_catalog"."default",
  "city" varchar(20) COLLATE "pg_catalog"."default",
  "updated_at" timestamp(6) NOT NULL,
  "created_at" timestamp(6) NOT NULL,
  "zz_app" varchar(500) COLLATE "pg_catalog"."default",
  "is_xray" int2 NOT NULL DEFAULT 0,
  "device" varchar(50) COLLATE "pg_catalog"."default",
  "is_use" int2 NOT NULL DEFAULT 0
)
;
COMMENT ON COLUMN "public"."server_nodes"."dw" IS '带宽';
COMMENT ON COLUMN "public"."server_nodes"."city" IS '地区或者国家';
COMMENT ON COLUMN "public"."server_nodes"."zz_app" IS '中转app';
COMMENT ON COLUMN "public"."server_nodes"."is_xray" IS '是否部署了xrary
';

-- ----------------------------
-- Table structure for server_stats
-- ----------------------------
DROP TABLE IF EXISTS "public"."server_stats";
CREATE TABLE "public"."server_stats" (
  "id" int8 NOT NULL,
  "node_id" int8 NOT NULL,
  "user_id" int8 NOT NULL,
  "u" int8,
  "d" int8,
  "app" varchar(16) COLLATE "pg_catalog"."default" NOT NULL,
  "updated_at" timestamp(6) NOT NULL,
  "method" varchar(15) COLLATE "pg_catalog"."default",
  "rate" varchar(10) COLLATE "pg_catalog"."default",
  "node_ip" varchar(32) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6) NOT NULL
)
;
COMMENT ON COLUMN "public"."server_stats"."app" IS 'app类型';

-- ----------------------------
-- Table structure for server_supplier_apis
-- ----------------------------
DROP TABLE IF EXISTS "public"."server_supplier_apis";
CREATE TABLE "public"."server_supplier_apis" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "key" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "secret" varchar(100) COLLATE "pg_catalog"."default",
  "note" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "supplier_account" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "supplier" varchar(40) COLLATE "pg_catalog"."default" NOT NULL,
  "status" int2 NOT NULL DEFAULT 0,
  "scope" int2 NOT NULL DEFAULT 0
)
;
COMMENT ON COLUMN "public"."server_supplier_apis"."scope" IS '0全球，不包含中国内地,1全球,2仅中国内地';

-- ----------------------------
-- Table structure for server_urls
-- ----------------------------
DROP TABLE IF EXISTS "public"."server_urls";
CREATE TABLE "public"."server_urls" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "url" varchar(1100) COLLATE "pg_catalog"."default" NOT NULL,
  "note" varchar(40) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for servers
-- ----------------------------
DROP TABLE IF EXISTS "public"."servers";
CREATE TABLE "public"."servers" (
  "id" int8 NOT NULL,
  "node_id" int4 NOT NULL,
  "host" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "app" varchar(16) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "port" int4 NOT NULL,
  "server_port" int4 NOT NULL,
  "parent_id" int4,
  "tags" varchar(255) COLLATE "pg_catalog"."default",
  "method" varchar(15) COLLATE "pg_catalog"."default",
  "out_host" varchar(255) COLLATE "pg_catalog"."default",
  "updated_at" timestamp(6)
)
;
COMMENT ON COLUMN "public"."servers"."app" IS 'app类型';

-- ----------------------------
-- Procedure structure for insert_server_bi_stats_hour
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."insert_server_bi_stats_hour"();
CREATE OR REPLACE PROCEDURE "public"."insert_server_bi_stats_hour"()
 AS $BODY$BEGIN
  -- Routine body goes here...
  INSERT INTO server_bi_tables (keys, val, type, times)
  SELECT 
      app AS keys,
      COUNT(DISTINCT user_id)::varchar AS val,
      2 AS type,
      date_trunc('minute', created_at) AS times
  FROM server_stats
  WHERE created_at >= date_trunc('hour', NOW()) - INTERVAL '1 hour'
    AND created_at <  date_trunc('hour', NOW())
  GROUP BY app,times
  ON CONFLICT (keys, type, times)
  DO UPDATE SET val = EXCLUDED.val;
END
$BODY$
  LANGUAGE plpgsql;

-- ----------------------------
-- Procedure structure for insert_server_bi_stats_yesterday
-- ----------------------------
DROP PROCEDURE IF EXISTS "public"."insert_server_bi_stats_yesterday"();
CREATE OR REPLACE PROCEDURE "public"."insert_server_bi_stats_yesterday"()
 AS $BODY$BEGIN
  -- Routine body goes here...
   INSERT INTO server_bi_tables (keys, val, type, times)
    SELECT 
        app AS keys,
        COUNT(DISTINCT user_id)::varchar AS val,
        1 AS type,
        (date_trunc('day', NOW()) - INTERVAL '1 day')::date AS times
    FROM server_stats
    WHERE created_at >= date_trunc('day', NOW()) - INTERVAL '1 day'
      AND created_at <  date_trunc('day', NOW())
    GROUP BY app
    ON CONFLICT (keys, type, times)
    DO UPDATE SET val = EXCLUDED.val;
END
$BODY$
  LANGUAGE plpgsql;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."server_bi_tables_id_seq"
OWNED BY "public"."server_bi_tables"."id";
SELECT setval('"public"."server_bi_tables_id_seq"', 207613, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."server_urls_copy1_id_seq"
OWNED BY "public"."server_hosts"."id";
SELECT setval('"public"."server_urls_copy1_id_seq"', 111, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."server_urls_copy1_id_seq1"
OWNED BY "public"."server_supplier_apis"."id";
SELECT setval('"public"."server_urls_copy1_id_seq1"', 9, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."server_urls_id_seq"
OWNED BY "public"."server_urls"."id";
SELECT setval('"public"."server_urls_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table server_bi_tables
-- ----------------------------
CREATE UNIQUE INDEX "uniq_server_bi_keys_type_times" ON "public"."server_bi_tables" USING btree (
  "keys" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "type" "pg_catalog"."int2_ops" ASC NULLS LAST,
  "times" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table server_bi_tables
-- ----------------------------
ALTER TABLE "public"."server_bi_tables" ADD CONSTRAINT "server_bi_table_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Uniques structure for table server_dicts
-- ----------------------------
ALTER TABLE "public"."server_dicts" ADD CONSTRAINT "server_dicts_key_type_key" UNIQUE ("key", "type");

-- ----------------------------
-- Primary Key structure for table server_dicts
-- ----------------------------
ALTER TABLE "public"."server_dicts" ADD CONSTRAINT "server_bi_tables_copy1_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table server_hosts
-- ----------------------------
CREATE UNIQUE INDEX "server_urls_url_idx_copy1" ON "public"."server_hosts" USING btree (
  "domain" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table server_hosts
-- ----------------------------
ALTER TABLE "public"."server_hosts" ADD CONSTRAINT "server_hosts_domain_key" UNIQUE ("domain");

-- ----------------------------
-- Primary Key structure for table server_hosts
-- ----------------------------
ALTER TABLE "public"."server_hosts" ADD CONSTRAINT "server_urls_copy1_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table server_logs
-- ----------------------------
CREATE UNIQUE INDEX "out_ip_copy1" ON "public"."server_logs" USING btree (
  "created_at" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table server_logs
-- ----------------------------
ALTER TABLE "public"."server_logs" ADD CONSTRAINT "server_nodes_copy1_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table server_nodes
-- ----------------------------
CREATE UNIQUE INDEX "out_ip" ON "public"."server_nodes" USING btree (
  "out_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "server_nodes_out_ip_out_ip_port_idx" ON "public"."server_nodes" USING btree (
  "out_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "out_ip_port" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table server_nodes
-- ----------------------------
ALTER TABLE "public"."server_nodes" ADD CONSTRAINT "server_stats_copy1_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table server_stats
-- ----------------------------
CREATE INDEX "idx_server_stats_created_app_user" ON "public"."server_stats" USING btree (
  "created_at" "pg_catalog"."timestamp_ops" ASC NULLS LAST,
  "app" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_server_stats_created_at_app_userid" ON "public"."server_stats" USING btree (
  "created_at" "pg_catalog"."timestamp_ops" ASC NULLS LAST,
  "app" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_server_stats_nodeip_created_at" ON "public"."server_stats" USING btree (
  "node_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "created_at" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);
CREATE INDEX "idx_server_stats_nodeip_createdat" ON "public"."server_stats" USING btree (
  "node_ip" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "created_at" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);
CREATE INDEX "idx_server_stats_trunc_day" ON "public"."server_stats" USING btree (
  date_trunc('day'::text, created_at) "pg_catalog"."timestamp_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table server_stats
-- ----------------------------
ALTER TABLE "public"."server_stats" ADD CONSTRAINT "server_stat_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table server_supplier_apis
-- ----------------------------
CREATE UNIQUE INDEX "server_urls_url_idx_copy2" ON "public"."server_supplier_apis" USING btree (
  "key" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table server_supplier_apis
-- ----------------------------
ALTER TABLE "public"."server_supplier_apis" ADD CONSTRAINT "server_urls_copy1_pkey1" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table server_urls
-- ----------------------------
CREATE UNIQUE INDEX "server_urls_url_idx" ON "public"."server_urls" USING btree (
  "url" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table server_urls
-- ----------------------------
ALTER TABLE "public"."server_urls" ADD CONSTRAINT "server_stats_users_copy1_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table servers
-- ----------------------------
CREATE INDEX "apps" ON "public"."servers" USING btree (
  "app" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_servers_app_nodeid" ON "public"."servers" USING btree (
  "app" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST,
  "node_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "nodeId" ON "public"."servers" USING btree (
  "node_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table servers
-- ----------------------------
ALTER TABLE "public"."servers" ADD CONSTRAINT "server_copy1_pkey" PRIMARY KEY ("id");
